### ISSUE TITLE
[question] Crossfeed in CamillaDSP

### ISSUE THREAD

**Issue by Ebert-Hanke** [Wang-Yue/camilladsp-crossfeed#1]
Very cool project! Someone form the moOde audio forum also just forwarded your new CamillaDSP-Monitor to me. I have been working on a tool to simply use AutoEq for CamillaDSP lately so it seems we have similar interests. Maybe there is a possibililty for contributing/ working together in the future. 

The moOde community would like to have some more options for crossfeed presets and I would like to test and "currate" a small list together with other audio enthusiasts.

This is the tool I am working on: https://github.com/Ebert-Hanke/autoeq2camilladsp
(I linked to your project since it came up while doing research on crossfeed in general)

**Comment by Wang-Yue** [comment]
Thanks for your warm message. 

I was one of the developer contributing to MPD but I've never had a chance to try moOde.
If you have an account on moOde forum please do me a favor introducing the CamillaDSP-Monitor there[*]. 
I believe someone will find that DSP flow interesting and try it. 

This project and the Monitor are mostly about studying how a mature product (ADI-2 DAC) tackles the interesting problem.
Everything released are verified to be identical to how ADI-2 does it (see the verification part in this project). Throughout the process I even found errors in ADI-2 and/or manual, reported them to RME, who fixed them immediately.. 
I believe it's also the first time the Digicheck (ADI-2 Spectrum Analyzer screen) got studied carefully outside RME and a clone released to the public.
Some parts of these research (crossfeed, digicheck, dc protection, etc) could be reused in other projects such as moOde.

[*] original introduction post [link](https://www.reddit.com/r/diyaudio/comments/sukhmu/camilladspmonitor_an_rme_adi2_dac_like_dsp_flow/)

**Comment by Ebert-Hanke** [comment]
It looks very interesting! I will try it later today on my machine. 
If you wanted to sign up for moOde forum yourself to promote the project: 
Forum applications work by short email now because of too many spam posts [see here](https://github.com/moode-player/moode/issues/477).
Otherwise I will mention it as well in the Crossfeed/DSP discussion.

RME is a great company and I do like what they do with DSP, it is great how thoroughly you "investigated" this!

I feel most crossfeed implementations lean on `b2bs` (coming from Linwitz, Moy, Meier) but I would really like to experiment a bit more and try other implementations since CamillaDSP offers so many possibilities. It would be fun to AB some tests and have a community rate their impressions at some point.

**Comment by Wang-Yue** [comment]
Please just start a thread to mention it. Many thanks.

**Comment by Ebert-Hanke** [comment]
Alright :)
So I will have a look at your CamillaDSP implementation of the Meier XF and might include it into [autoeq2camilladsp](https://github.com/Ebert-Hanke/autoeq2camilladsp). If I do I will link you as a resource together with Meier's original publication on the analogue implementation and Mikhaylov's version in `bs2b` in the readme section about the Crossfeed presets. I also signed up for diyAudio so hope to see you there! Thanks for the great work!

**Comment by Wang-Yue** [comment]
Yeah I signed up diy audio earlier today and here's the post there: https://www.diyaudio.com/community/threads/camilladsp-monitor-a-rme-adi-2-dac-like-dsp-flow.383193/

**Comment by Ebert-Hanke** [comment]
See you there then!
